blueprint:
  name: Unavailable Entities in Integration 
  description: Regularly test all sensors in a certain integration on availability.
  domain: automation
  source_url: https://github.com/bjorntimmer/homeassistant_blueprints/blob/main/unavailable_entities_in_integration_notification/unavailable_entities_in_integration_notification.yaml


  # Blueprint Inputs
  input:
    integration:
      name: Give the integration name
      description: Give the integration name
      default: 'zha'
      selector:
        text:
    time:
      name: Time to test on
      description: Test is run at configured time
      default: '10:00:00'
      selector:
        time: {}
    # In this segment the user will selected the week days that te automation will be exectuted.
    monday_enabled:
      name: 'Monday'
      description: 'Run test on Monday'
      default: True
      selector:
        boolean:
    tuesday_enabled:
      name: Tuesday
      description: 'Run test on Tuesday'
      default: True
      selector:
        boolean:
    wednesday_enabled:
      name: Wednesday
      description: 'Run test on Wednesday'
      default: True
      selector:
        boolean:
    thursday_enabled:
      name: Thursday
      description: 'Run test on Thursday'
      default: True
      selector:
        boolean:
    friday_enabled:
      name: Friday
      description: 'Run test on Friday'
      default: True
      selector:
        boolean:
    saturday_enabled:
      name: Saturday
      description: 'Run test on Saturday'
      default: True
      selector:
        boolean:
    sunday_enabled:
      name: Sunday
      description: 'Run test on Sunday'
      default: True
      selector:
        boolean:

    exclude:
      name: Excluded Sensors
      description: Sensors (e.g. smartphone) to exclude from detection. Only entities are supported, areas and devices must be expanded!
      default: {}
      selector:
        target:
          entity:
            device_class: battery


    actions:
      name: Actions
      description: Notifications or similar to be run. {{entities}} is replaced with the names of sensors being low on battery.
      selector:
        action:


variables:
  monday_enabled: !input 'monday_enabled'
  tuesday_enabled: !input 'tuesday_enabled'
  wednesday_enabled: !input 'wednesday_enabled'
  thursday_enabled: !input 'thursday_enabled'
  friday_enabled: !input 'friday_enabled'
  saturday_enabled: !input 'saturday_enabled'
  sunday_enabled: !input 'sunday_enabled'

  current_day: '{{ now().weekday() | int }}'

  integration: !input 'integration'

  exclude: !input 'exclude'

  sensors: >-
    {% set result = namespace(entities=[]) %}
    {% for entity_id in integration_entities('zha') and entity_id not in exclude.entity_id %}
      {% if states(entity_id) == 'unavailable' %}
        {% set result.entities = result.entities + [state_attr(entity_id, 'friendly_name')] %}
      {% endif %}
    {% endfor %}
    {{"⤵ \n- "}}{{result.entities|sort|join('\n- ')}}


# Triggers
trigger:
  - platform: time
    at: !input 'time'


# Conditions used to determine if the automation should run for the specific trigger event
condition:
# Check if the automation is supposed to be executed during that specific weekday
  - condition: template
    value_template: >-
        {{ 
          (current_day == 0 and monday_enabled) or 
          (current_day == 1 and tuesday_enabled) or 
          (current_day == 2 and wednesday_enabled) or
          (current_day == 3 and thursday_enabled) or 
          (current_day == 4 and friday_enabled) or
          (current_day == 5 and saturday_enabled) or
          (current_day == 6 and sunday_enabled)
        }}


  # Check if the sensors list is not empty
  - condition: template
    value_template: >-
        {{ entities != "⤵ \n-"}}


# Actions
action:
  - choose: []
    default: !input 'actions'
  
mode: single
max_exceeded: silent
